### ISSUE TITLE
Expose retry timeout configuration

### ISSUE THREAD

**Issue by SharkFourSix** [tmaxmax/go-sse#20]
Hi here. Good library.

I would like to keep my client connection forever as long as I want but with the ability to cancel.

Cancelling is not a problem, but it seems configuring the retry option is not baked into the code. Can this be done?

Currently I do not even know what the max retry backoff is so I'm in the dark on that one. It seems like the only way is to enclose the `conn.Connect()` inside a loop, but that doesn't feel right because it's already handling the timing inside.

**Comment by tmaxmax** [comment]
Hi there and thank you for raising this issue!

Just to make sure I understand, what you're looking for is more control over the backoff strategy. Currently you can configure the client to keep reconnecting indefinitely:
```go
client := sse.Client{
    MaxRetries: -1, // -1 is interpreted as unbounded reconnection attempt count
}
conn := client.NewConnection(...) // use the client as normal
```
What you indeed cannot do is for example change the backoff algorithm or set a maximum backoff. As of now, the behavior of the backoff is the following:
- the backoff period grows exponentially
- the maximum backoff is 60 seconds
- the maximum duration that backoff can be attempted is 15 minutes – that is, after 15 minutes, the client will stop the reconnection attempts

The client also respects any `retry` fields sent by the server. Does your use case also require overriding this behavior? To what other parameters would you need access?

Let me know if I've grasped the problem at hand correctly!

**Comment by SharkFourSix** [comment]
@tmaxmax Thanks for the response. You understood my question. 

Now, looking at the  documentation, specifically this line

https://github.com/tmaxmax/go-sse/blob/4d09371fe868fffe25d67f41891bd4e243790621/client.go#L46

Does it mean after a graceful disconnect, the next reconnect will revert back to `0`?

One other thing that I also initially forgot to include was cancellation/shutdown of the client.

I want to have something like this:

```go
connectfn := func(){
    err := client.Connect()
    if err != nil {
        switch e := err.(type) {
            case <whatErrorGoesHereToSignalIntentionalCancellation> :
                disconnectedSignal <- true
            default:
                log.Errorf("Connection failed. Reconnecting in %v", retryWait)
                time.Sleep(retryWait)
                reconnectSignal <- true
        }
    }else{
        log.Log("Connected")
    }
}
go connectfn()
for {
    select {
        case shutdownSignal: // received from external service controller, CTRL+C, process manager, SIGTERM, etc
            // what to do here to tell the client to disconnect?
            client.Disconnect() ??
        case disconnectedSignal:
            // do some cleanup
            return
        case reconnectSignal:
            go connectfn()
    }
}
```

**Comment by tmaxmax** [comment]
> Does it mean after a graceful disconnect, the next reconnect will revert back to `0`?

That means not that `MaxRetries` itself will be set to 0, but the internal retries counter. For example, if `MaxRetries` is 5, 4 attempts were made to reconnect and the last is successful, then, on an another eventual network issue, if the retries counter would not be reset, then the client would attempt only one time to reconnect, as `MaxRetries` is 5 and in total 5 retries were made. With the current behaviour the client attempts at most `MaxRetries` times for each connection loss, not in total. In other words, `MaxRetries` means "how many attempts can I make until I reconnect successfully", not "how many attempts can I make across the total lifespan of the `Connection` object".

> One other thing that I also initially forgot to include was cancellation/shutdown of the client.

You can use the request context to signal shutdown/cancellation:
```go
ctx, cancel := context.WithCancel(context.Background()) // or signal.NotifyContext(...) etc.
defer cancel()

req, _ := http.NewRequestWithContext(ctx, http.MethodGet, "https://example.com/sse", http.NoBody)
conn := client.NewConnection(req)

// configure the connection

go func() {
    err := conn.Connect()
    // Handle error here.
    // On cancellation this will be the error of the request context (in this code ctx.Err())
}

for {
    select {
    case shutdownSignal:
        cancel() // This will close the connection
    }
}
```

Regarding your initial problem, it seems like you would need access to more configuration of the backoff. Would something like:
```go
type Client struct {
    // ...the other fields

    // Backoff is a function which creates a Backoff object
    // to be used by connections. This configures the backoff behavior,
    // refer to the cenkalti/backoff documentation for a reference of the
    // config options.
    //
    // The backoff is reset after each reconnection, and `retry` fields sent
    // from the server change the initial backoff interval, in line with
    // browser behavior.
    //
    // Each call to this function should return a new object. Otherwise
    // when multiple connections are used they will share the same backoff
    // configuration and bugs will emerge.
    Backoff func() backoff.Backoff
}
```
Would be used like:
```go
client := sse.Client{
    Backoff: func() backoff.Backoff {
        return backoff.NewExponentialBackOff(
            backoff.WithInitialInterval(time.Second * 3),
            backoff.WithMultiplier(2),
            backoff.WithMaxElapsedTime(0), // unbounded
        )
    }
}
req, _ := /* build HTTP request */
// This Connection object will retry to re-establish connection to the server forever,
// start with a delay of 3 seconds which is doubled on each subsequent attempt.
conn := client.NewConnection(req)
```

**Comment by SharkFourSix** [comment]
Everything looks great so far.

You are actually right that I would need access to the backoff settings because I want a constant retry wait period due to the time-sensitive  nature of my service.

**Comment by tmaxmax** [comment]
Are you on a tight deadline with this? I will take a little longer to implement the changes because I'd like to explore some alternative API possibilities besides what I've come up with above and maybe even removing the dependency on the external backoff library.

If you need this ASAP here's what you could do: make a fork of the library and change [this code](https://github.com/tmaxmax/go-sse/blob/4d09371fe868fffe25d67f41891bd4e243790621/client.go#L79-L94) with the following:
```go
func (c *Client) newBackoff(ctx context.Context) (b backoff.BackOff, setRetry func(time.Duration)) {
	base := backoff.NewConstantBackOff(c.DefaultReconnectionTime)
	b = backoff.WithContext(base, ctx)
	if c.MaxRetries >= 0 {
		rb := backoff.WithMaxRetries(b, uint64(c.MaxRetries))
		return rb, func(d time.Duration) {
			base.Interval = d
			rb.Reset()
		}
	}
	return b, func(d time.Duration) {
		base.Interval = d
		b.Reset()
	}
}
```

This will give you a backoff with constant retry period of `client.DefaultReconnectionTime` duration. You could use your own fork in your code until the next release.

Would this work for you as a temporary solution?

**Comment by SharkFourSix** [comment]
I tried this solution (https://github.com/SharkFourSix/go-sse) but did not succeed because go won't let me import the forked repo due to package declarations being broken. For a temporary solution, using the "replace" trick doesn't look like a good idea either. And yes, I sort of needed it sooner. But no pressure. I could look for alternatives. Although, simply exposing an option to disable the backoff with a no-op adapter could also work :smiley: 


Btw, I know this is unrelated but I just came across this just now

![image](https://github.com/tmaxmax/go-sse/assets/18681730/faef03a3-6819-4107-aea8-baa6b78d7c5e)

**Comment by tmaxmax** [comment]
> because go won't let me import the forked repo due to package declarations being broken

Oh, yeah... totally forgot about that. I apologize. I've taken a short break and a new solution occurred to me. I've pushed a branch with the fix ([`constant-backoff`](https://github.com/tmaxmax/go-sse/tree/constant-backoff)) which you should be able to use instead of the latest release. Something like:
```sh
$ go get github.com/tmaxmax/go-sse@constant-backoff
```

If somehow this also doesn't work, there would be one more thing possible... You could set `MaxRetries` to 1, the `DefaultReconnectionTime` to whatever you wish the backoff period to be, and then execute `Connect` in a loop:
```go
client := sse.Client{
    MaxRetries: 1,
    DefaultReconnectionTime: 2 * time.Second
}
req, _ := http.NewRequestWithContext(ctx, ...)
conn := client.NewConnection(req)

// setup your message listeners

for !errors.Is(conn.Connect(), ctx.Err()) {
    // We don't have to do anything here.
    // The connection is retried one single time after two seconds.
    // If that retry fails, the request error is returned, and given that
    // it is not the context error the connection will be reattempted.
    // This is effectively a constant backoff retry strategy.
}

// if this point is reached then the context was cancelled
```

Regarding that vulnerability, `gopkg.in/yaml` is a transitive dependency of a test dependency (`testify`) of `go-sse`. It is not used in the library code, neither in the server, nor in the client. I should update the dependencies, but there's nothing to worry about for library users.

Please let me know if any of these two ideas solves your issue!
