### ISSUE TITLE
Client drops messages longer than 4096 bytes

### ISSUE THREAD

**Issue by aldld** [tmaxmax/go-sse#3]
Hello! I've been using `go-sse` lately and have been enjoying it a lot. One issue that I came across recently is that messages that are longer than 4096 bytes get dropped by the client. I narrowed this down to an issue with how we parse messages from the event stream.

PR #2 contains a test case that reproduces this bug, along with a fix. Let me know if you have any questions, or need more information!

**Comment by tmaxmax** [comment]
Thank you for raising the issue and opening the PR! See the PR for code-related discussions.

I know I haven't contributed to the library in a long while, given time issues and that I've shifted my attention to other projects. Nevertheless, I'm still here and able to maintain it again, so if you find any bugs or non-conformities with the specification, have suggestions for new features or find cleaner or more performant ways to implement things internally, please let me know! The goal of `go-sse` is to be correct, idiomatic and performant.

Feel free to close the issue yourself when the PR is merged, i.e. issue is fixed.
